const sub=['maths','social']
console.log(Array.isArray(sub))
console.log(sub.includes('social',2))
console.log(sub.push('science','kannada'))
console.log(sub.pop())
console.log(sub)
console.log(sub.unshift('english'))
console.log(sub)
sub.shift()
console.log(sub)
const sub1=sub.splice(2,2,'g.k')
console.log(sub1)
console.log(sub)
const sub2=sub.slice(1,3)
console.log(sub2)
const sub3=sub.join('_')
console.log(sub3)
console.log(sub.indexOf('Abbey',2))
sub.map(function(value,index){
    console.log(sub[index],index)
})
sub.filter(function(val,ind){
    console.log(ind)
})
console.log('========================================')
const even=[2,4,6]
console.log(Array.isArray(even))
console.log(even.includes(4,2))
even.push(8)
console.log(even)
even.pop()
console.log(even)
even.unshift(10,12)
console.log(even)
even.shift()
console.log(even)
even.splice(3,1)
console.log(even)
const even1=even.slice(1,2)
console.log(even1)
const even2=even.join('+')
console.log(even2)
console.log(even.indexOf(10,1))
console.log('========================================')
const color=['white','black']
console.log(Array.isArray(color))
console.log(color.includes('black',1))
color.push('pink')
console.log(color)
color.pop()
console.log(color)
color.unshift('blue')
console.log(color)
color.shift()
console.log(color)
color.splice(1,2,'orange')
console.log(color)
const color1=color.slice(2,3)
console.log(color1)
const color3=color.join('1')
console.log(color3)
const color2=color.indexOf('voilet',2)
console.log(color2)
console.log('========================================')
const veg=['chilly','tomato']
console.log(Array.isArray(veg))
console.log(veg.includes('potato',3))
console.log(veg.push('potato'))
veg.pop()
console.log(veg)
veg.unshift('sweet potato','drumstick')
console.log(veg)
veg.shift()
console.log(veg)
veg.splice(2,1,'carrot')
console.log(veg)
const veg1=veg.slice(0,2)
console.log(veg1)
const veg2=veg.join('#')
console.log(veg2)
console.log(veg.indexOf('raddish',2))
console.log('========================================')
const trees=['neem','peepal','amla','banyan']
console.log(Array.isArray(trees))
console.log(trees.includes('amla',1))
console.log(trees.push('aloe vera'))
trees.pop()
console.log(trees)
trees.unshift('tulasi')
console.log(trees)
trees.shift()
console.log(trees)
trees.splice(2,1,'tulasi')
console.log(trees)
const tree1=trees.slice(0,2)
console.log(tree1)
const tree2=trees.join('@')
console.log(tree2)
console.log(trees.indexOf('peepal',3))
console.log('========================================')
const flys=['bee','dragonfly']
console.log(Array.isArray(flys))
console.log(flys.includes('spider',1))
console.log(flys.push('house fly'))
flys.pop()
console.log(flys)
flys.unshift('caterpillar')
console.log(flys)
flys.shift()
console.log(flys)
flys.splice(0,2,'caterpillar')
console.log( flys)
const fly1=flys.slice(0,1)
console.log(fly1)
const fly2=flys.join('$')
console.log(fly2)
console.log(flys.indexOf('caterpillar',0))
console.log('========================================')
const prime=[2,3]
console.log(Array.isArray(prime))
console.log(prime.includes(3,3))
console.log(prime.push(5))
prime.pop()
console.log(prime)
prime.unshift(7)
console.log(prime)
prime.shift()
console.log(prime)
prime.splice(1,2,7)
console.log(prime)
const pri1=prime.slice(0,1)
console.log(pri1)
const pri2=prime.join('&')
console.log(pri2)
console.log(prime.indexOf(7,1))
console.log('========================================')
const fever=['dengue','viral']
console.log(Array.isArray(fever))
console.log(fever.includes('dengue',0))
console.log(fever.push('lassa','jaundice'))
fever.pop()
console.log(fever)
fever.unshift('jaundice')
console.log(fever)
fever.shift()
console.log(fever)
fever.splice(1,1,'jaundice')
console.log(fever)
const fev1=fever.slice(0,2)
console.log(fev1)
const fev2=fever.join('^')
console.log(fev2)
console.log(fever.indexOf('dengue',0))
console.log('========================================')
const place=['kadur','bang']
console.log(Array.isArray(place))
console.log(place.includes('kadur',0))
console.log(place.push('birur'))
place.pop()
console.log(place)
place.unshift('mysore')
console.log(place)
place.shift()
console.log(place)
place.splice(1,2,'mysore')
console.log(place)
const pla1=place.slice(1,2)
console.log(pla1)
const pal2=place.join('*')
console.log(pal2)
console.log(place.indexOf('maxico',0))
console.log('========================================')
const food=['pani puri','masala puri']
console.log(Array.isArray(food))
console.log(food.includes('pani puri',1))
console.log(food.push('gobi'))
food.pop()
console.log(food)
food.unshift('kachori')
console.log(food)
food.shift()
console.log(food)
food.splice(0,1,'pav bhaji')
console.log(food)
const food1=food.slice(1,3)
console.log(food1)
const food2=food.join('!')
console.log(food2)
console.log(food.indexOf('gobi',1));